version: '3.1'
services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: baya
            POSTGRES_PASSWORD: 123456789
            POSTGRES_DB: fuel_consumption
        ports:
            - "5432:5432"
        volumes:
            - ./create_tables.sql:/docker-entrypoint-initdb.d/start.sql

  